language: node_js
node_js:
  - "10"

sudo: required
services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.21.1
  matrix:
    - PLUGIN=dynamodb-streams-readable
    - PLUGIN=serverless-offline-kinesis
    - PLUGIN=serverless-offline-dynamodb-streams
    - PLUGIN=serverless-offline-sqs
    - PLUGIN=serverless-offline-ssm-provider


before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install: npm install

before_script:
  - docker-compose up -d

script:
  - npm run lint
  - npm run test -- packages/$PLUGIN/test

after_success:
  - npm run cover
